
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 19 19:14:04 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 37;
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 39;
  public static final int REM = 26;
  public static final int GREATER = 40;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int CONTINUE = 32;
  public static final int LESS = 42;
  public static final int MINUS = 21;
  public static final int CHARACTER = 47;
  public static final int RPAREN = 13;
  public static final int AND = 35;
  public static final int LESSEQUAL = 43;
  public static final int OR = 34;
  public static final int BOOL = 46;
  public static final int COMMA = 8;
  public static final int INC = 19;
  public static final int DIV = 25;
  public static final int PLUS = 23;
  public static final int ASSIGN = 7;
  public static final int IF = 28;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 38;
  public static final int RBRACKET = 10;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 45;
  public static final int IDENT = 44;
  public static final int BREAK = 31;
  public static final int VOID = 11;
  public static final int GREATEREQUAL = 41;
  public static final int COLON = 14;
  public static final int UNION = 36;
  public static final int LBRACE = 3;
  public static final int ELSE = 33;
  public static final int READ = 16;
  public static final int GOTO = 18;
  public static final int WHILE = 30;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 20;
  public static final int PRINT = 17;
  public static final int DO = 29;
}

